### ISSUE TITLE
demo都跑不起来.. 

### ISSUE THREAD

**Issue by thisCookie** [colinsusie/excelexporter#2]
![image](https://user-images.githubusercontent.com/8164795/115703925-46537680-a39d-11eb-92d0-05b0493ee607.png)

**Comment by LiuYinCarl** [comment]
测试用例确实存在问题。
第一个测试 需要你先在 test/ 目录下创建一个 out/ 目录。
 第二个测试错误的原因是test/ 目录下不存在 `test1.py` 这个文件，你需要改成 `python3 excel_exporter.py -p ./test/测试文件1.py`

可能是作者测试的时候没有测试到。

**Comment by thisCookie** [comment]
可以了. thinks

**Comment by colinsusie** [comment]
我已经更新了测试文件的路径，和README文档。
